baseURL                = "https://ice-energy.github.io/sharedhugo"
languageCode           = "en-us"
defaultContentLanguage = "en"
title                  = "IceEnergySharedHugo"
theme                  = "dream-plus"
canonifyURLs           = false

pygmentsCodeFences = true
pygmentsUseClasses = true
pygmentsOptions    = "linenos=table"

#disqusShortname = "dream-plus"
enableRobotsTXT  = true
enableEmoji      = true

[params]
	author           = "Ice-Energy"
	description      = "A Placeholder for Ice-Energy Notes & Documentation"
	avatar           = "img/icelogo.jpg"
	motto            = "Where we go One, We go All"
	enableToc        = true
	#enableShareCard = true

	favicon = "img/defaultFav.ico"
  	
  	#Background settings
	#enableColorBG = false
	#bgBlur        = "0px"
	#bgImage       = "http://bit.ly/2gPLxZ4"
  
	#Post-displaying Settings
	enableTags       = true
	enableCategories = true

	itemsPerPage = 6                          # Cards or posts shown per page
	contentType = "post"                      # Set whether you're hosting "cards" or "post"
	#twitterEmoji=true

[social]
	email         = "software@ice-energy.com"
	github        = "ice-energy/sharedhugo"
	siteStartYear = 2018
